# Generated by Django 3.2.10 on 2026-01-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje / Consulta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Contacto')),
            ],
            options={
                'verbose_name': 'Lead Web',
                'verbose_name_plural': 'Leads Web (Consultas)',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
