# Generated by Django 5.2.9 on 2026-05-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitudasesoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudasesoria',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudasesoria',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudasesoria',
            name='gateway',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudasesoria',
            name='monto',
            field=models.DecimalField(decimal_places=0, default=60000, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudasesoria',
            name='token_transaccion',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
